name: Deploy with YouTube API
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Inject API Key
        run: |
          mkdir -p js
          echo "const API_KEY = '${{ secrets.YT_API_KEY }}';" > js/config.js
          echo "const CHANNEL_ID = 'UCcpMp0LFsZ3mX2TSVgfk1ow';" >> js/config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./