name: Deploy YouTube Channel Website
on: 
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Create config directory
        run: mkdir -p js
        
      - name: Inject API Key
        run: |
          echo "const API_KEY = '${{ secrets.YT_API_KEY }}';" > js/config.js
          echo "const CHANNEL_ID = 'UCcpMp0LFsZ3mX2TSVgfk1ow';" >> js/config.js
          echo "export { API_KEY, CHANNEL_ID };" >> js/config.js
          
      - name: Install dependencies (if needed)
        run: npm install
        
      - name: Build project (if needed)
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
