name: Deploy with YouTube API
on: [push]  # Jalankan otomatis saat push ke GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          echo "const API_KEY = '${{ secrets.YT_API_KEY }}';" > js/config.js
          echo "const CHANNEL_ID = 'UCcpMp0LFsZ3mX2TSVgfk1ow';" >> js/config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./